#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "dry/cli"

cli = Dry::CLI.new(ActivityMonitor::CLI)
ActivityMonitor::CLI::Bundler.require(:cli)

begin
  cli.call
rescue ActivityMonitor::CLI::Error => exception
  $stderr.puts(exception.message)
  exit(1)
end
